### Создание брони
POST {{host}}/api/v1/booking
Content-Type: application/json
Accept: application/json

{
    "user_id": 1,
    "room_id": 1,
    "start_at": "2025-07-15 6:00:00",
    "end_at": "2025-07-20 17:00:00"
}
